### ISSUE TITLE
Unknown push notifications enabled

### ISSUE THREAD

**Issue by JPNavilo** [Swrve/swrve-ios-sdk#230] opened 2017-01-31 15:27 UTC
We realize that in the newer version of one app that we are using Swrve services, user are always sending that their push notifications are unknown.
I just debug the code and I realize that although:
pushSettingsEnabled = [app isRegisteredForRemoteNotifications];
it is YES we are returning the unknown state.
I think the problem could be in this last commit.
https://github.com/Swrve/swrve-ios-sdk/commit/09b368d0bf75c7e11c529b4ed5208ef5d6dd6252 
Thank you for your attention.

**Comment by Sergio-Mira** [comment] 2017-01-31 15:34
Hi @JPNavilo you are indeed correct. The left over 'else' is probably causing the issue. We'll fix it in the next release. Thanks!

**Comment by clue4gd** [comment] 2017-03-22 15:21
Is there a fix added in the current release 4.9? Still having a problem timing the push notification request with a list of push notification events and i suspect thats due to this issue.
SwrveConfig* config = [[SwrveConfig alloc] init];
config.pushEnabled = YES;
config.pushNotificationEvents = [[NSSet alloc] initWithArray:@[@"push_notification_permission"]];
[Swrve sharedInstanceWithAppID:[appId intValue] apiKey:apiKey config:config]
..but the request permission popup appears immediately on app start.

**Comment by Sergio-Mira** [comment] 2017-03-22 15:42
Yes, we added a fix for this issue in the latest release 4.9.
@clue4gd did your problem started on a given release or is it the first integration? Do you happen to do location targeting too? The library we use has a know issue where it asks for push permissions always at the start.

**Comment by clue4gd** [comment] 2017-03-23 08:36
Its not the first integration but i can't check versions below 4.6. On 4.6 the popup appears immediately on app start already. On this app, we are not doing any location targeting.
Is there a bug task for it or is it planned to have this fixed in one of the next releases?

**Comment by Sergio-Mira** [comment] 2017-03-23 14:34
@clue4gd I cannot reproduce the issue in any of our versions given that config. The issue that the original author had is not related to asking for permissions but reporting on them once that has happened for user segmentation.

If you take [the following sample bundled with the SDK](https://github.com/Swrve/swrve-ios-sdk/tree/release-4_6/samples/Objective-C/MessageCenterSample) and use that config in the AppDelegate the permission dialog does not appear until the event is sent. If you remove the configured push events it does request right away as expected.

The easiest way to find out where your permission request is coming from would be to put a breakpoint in `ISHPermissionRequestNotificationsRemote` method `registerForRemoteNotifications`.

If you continue having issues please get it contact with support@swrve.com and if possible provide a way to reproduce the issue. Thanks!

**Closed as completed by Sergio-Mira** 2017-03-23 14:34 UTC
Labels: bug
