### ISSUE TITLE
Payloads of events not visible in Swrve Console

### ISSUE THREAD

**Issue by ivanvranjic** [Swrve/swrve-ios-sdk#240] opened 2018-03-02 17:25 UTC
This is an example of json body that is sent to `https://<app_id>.api.swrve.com/1/batch`
`{"user":"XXX","short_device_id":18003,"app_version":"1.0","session_token":"XXX","data":[{"payload":{"screen_name":"settings","button_name":"share"},"seqnum":1728,"name":"appname.top_level.press_button","type":"event","time":1520010244863}],"version":2}`
I see this when I debug network requests in the app.

Events are recorded and visible in Swrve console but payloads are missing.
<img width="699" alt="screen shot 2018-03-02 at 18 25 16" src="https://user-images.githubusercontent.com/7572280/36912477-197cd1bc-1e47-11e8-96be-1c72bd2d36ac.png">

**Comment by Sergio-Mira** [comment] 2018-03-02 19:04
I believe that has to be enabled in the backend, could you please get in contact with support@swrve.com?

**Comment by ejmartin504** [comment] 2018-04-03 14:12
I can confirm that is not enabled by default on the backend. Have spoken with Swrve quite a bit about this, still not 100% sure why this is the case.

**Comment by Sergio-Mira** [comment] 2018-04-25 11:08
Hi @ejmartin504 did you manage to get the event payloads processed?

**Comment by ejmartin504** [comment] 2018-04-25 14:08
This was a while back, but I was told that they could enable it for me, but that it would adversely affect other reporting somehow. Sorry I don't remember exactly all the details

**Comment by Sergio-Mira** [comment] 2018-05-02 11:11
Closing this issue for now as it is due to a feature in the backend. Please reopen or get in contact with support@swrve.com if you have further questions. Thanks!

**Closed as completed by Sergio-Mira** 2018-05-02 11:11 UTC
